import {
  collection,
  doc,
  getDocs,
  setDoc,
  deleteDoc,
  addDoc,
  onSnapshot,
  query,
  where,
  orderBy,
  serverTimestamp,
} from 'firebase/firestore';
import { db, handleFirestoreError, OperationType } from '../firebase';
import { DurianFarm, IndividualTree } from '../types';
import { INITIAL_DURIAN_FARMS } from '../data/farms';

const FARMS_COLLECTION = 'farms';
const REVIEWS_COLLECTION = 'reviews';

export interface FirestoreReviewDoc {
  id?: string;
  treeCode: string;
  farmId: string;
  authorName: string;
  rating: number;
  comment: string;
  date: string;
  verifiedNfcTag?: string;
  nfcScannedFruitUid?: string;
  isVerifiedBuyer: boolean;
  flavorNotes?: string[];
  createdAt?: any;
}

/**
 * Deep cleans an object before sending to Firestore, eliminating any undefined values
 */
function sanitizeForFirestore(data: any): any {
  if (data === null || data === undefined) {
    return null;
  }
  if (Array.isArray(data)) {
    return data.map((item) => sanitizeForFirestore(item));
  }
  if (typeof data === 'object' && !(data instanceof Date)) {
    const cleaned: Record<string, any> = {};
    for (const [key, value] of Object.entries(data)) {
      if (value !== undefined) {
        cleaned[key] = sanitizeForFirestore(value);
      }
    }
    return cleaned;
  }
  return data;
}

/**
 * Seed all initial sample farms into Firestore and ensure all 6 farms exist
 */
export async function seedFarmsIfEmpty(): Promise<DurianFarm[]> {
  try {
    const snapshot = await getDocs(collection(db, FARMS_COLLECTION));
    const existingMap = new Map<string, DurianFarm>();
    
    snapshot.forEach((d) => {
      existingMap.set(d.id, d.data() as DurianFarm);
    });

    // If any initial farm is missing, seed it to Firestore
    for (const farm of INITIAL_DURIAN_FARMS) {
      if (!existingMap.has(farm.id)) {
        const cleanedFarm = sanitizeForFirestore(farm);
        await setDoc(doc(db, FARMS_COLLECTION, farm.id), {
          ...cleanedFarm,
          updatedAt: serverTimestamp(),
        });
        existingMap.set(farm.id, farm);
      }
    }

    const allFarms = Array.from(existingMap.values());
    allFarms.sort((a, b) => (a.rank || 99) - (b.rank || 99));
    return allFarms;
  } catch (err) {
    handleFirestoreError(err, OperationType.GET, FARMS_COLLECTION);
    return INITIAL_DURIAN_FARMS;
  }
}

/**
 * Listen to real-time updates from Firestore farms collection
 */
export function subscribeFarms(
  onFarmsUpdated: (farms: DurianFarm[]) => void
): () => void {
  const q = collection(db, FARMS_COLLECTION);
  return onSnapshot(
    q,
    (snapshot) => {
      if (snapshot.empty || snapshot.size < INITIAL_DURIAN_FARMS.length) {
        // If incomplete or empty, auto-seed and return full list
        seedFarmsIfEmpty().then((f) => onFarmsUpdated(f));
        return;
      }
      const rawFarms: DurianFarm[] = [];
      snapshot.forEach((docSnap) => {
        const data = docSnap.data() as DurianFarm;
        rawFarms.push({ ...data, id: docSnap.id });
      });

      // Deduplicate: If multiple documents share the exact same name & province & managerId,
      // keep only one and delete the orphaned redundant copy from Firestore
      const uniqueFarmsMap = new Map<string, DurianFarm>();
      const seenNameProvince = new Set<string>();

      for (const farm of rawFarms) {
        if (!farm || !farm.name) continue;

        // Auto-cleanup any unapproved / test-created farm from previous test runs
        if (farm.name === '123123123' || farm.id.includes('123123123')) {
          deleteDoc(doc(db, FARMS_COLLECTION, farm.id)).catch(() => {});
          continue;
        }

        const key = farm.id;
        const dedupeSignature = `${(farm.name || '').trim()}_${(farm.province || '').trim()}_${(farm.managerId || '').trim()}`;

        if (seenNameProvince.has(dedupeSignature)) {
          // If this is a duplicate generated by multiple clicks, delete redundant duplicate doc
          if (farm.id.startsWith('farm-') && !INITIAL_DURIAN_FARMS.some((init) => init.id === farm.id)) {
            console.log('Cleaning up duplicate farm document:', farm.id, farm.name);
            deleteDoc(doc(db, FARMS_COLLECTION, farm.id)).catch(() => {});
          }
          continue;
        }

        seenNameProvince.add(dedupeSignature);
        uniqueFarmsMap.set(key, farm);
      }

      const farms = Array.from(uniqueFarmsMap.values());
      farms.sort((a, b) => (a.rank || 99) - (b.rank || 99));
      onFarmsUpdated(farms);
    },
    (error) => {
      handleFirestoreError(error, OperationType.LIST, FARMS_COLLECTION);
      onFarmsUpdated(INITIAL_DURIAN_FARMS);
    }
  );
}

/**
 * Delete a farm from Firestore
 */
export async function deleteFarmFromFirestore(farmId: string): Promise<void> {
  try {
    await deleteDoc(doc(db, FARMS_COLLECTION, farmId));
  } catch (err) {
    handleFirestoreError(err, OperationType.DELETE, FARMS_COLLECTION);
    throw err;
  }
}

/**
 * Save a new or updated farm to Firestore
 */
export async function saveFarmToFirestore(farm: DurianFarm): Promise<void> {
  try {
    const cleanedFarm = sanitizeForFirestore(farm);
    await setDoc(doc(db, FARMS_COLLECTION, farm.id), {
      ...cleanedFarm,
      updatedAt: serverTimestamp(),
    });
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, FARMS_COLLECTION);
    throw err;
  }
}

/**
 * Add / Save a verified tree review to Firestore
 */
export async function saveReviewToFirestore(review: FirestoreReviewDoc): Promise<string> {
  try {
    const cleanedReview = sanitizeForFirestore(review);
    const docRef = await addDoc(collection(db, REVIEWS_COLLECTION), {
      ...cleanedReview,
      createdAt: serverTimestamp(),
    });
    return docRef.id;
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, REVIEWS_COLLECTION);
    throw err;
  }
}

/**
 * Add review (alias for saveReviewToFirestore)
 */
export const addReviewToFirestore = saveReviewToFirestore;

/**
 * Listen to real-time reviews for a specific tree from Firestore
 */
export function subscribeTreeReviews(
  treeCode: string,
  onReviewsUpdated: (reviews: FirestoreReviewDoc[]) => void
): () => void {
  const q = query(
    collection(db, REVIEWS_COLLECTION),
    where('treeCode', '==', treeCode)
  );

  return onSnapshot(
    q,
    (snapshot) => {
      const reviews: FirestoreReviewDoc[] = [];
      snapshot.forEach((docSnap) => {
        reviews.push({ id: docSnap.id, ...docSnap.data() } as FirestoreReviewDoc);
      });
      onReviewsUpdated(reviews);
    },
    (error) => {
      handleFirestoreError(error, OperationType.LIST, REVIEWS_COLLECTION);
    }
  );
}

/**
 * Fetch reviews for a specific tree from Firestore
 */
export async function getTreeReviewsFromFirestore(treeCode: string): Promise<FirestoreReviewDoc[]> {
  try {
    const q = query(
      collection(db, REVIEWS_COLLECTION),
      where('treeCode', '==', treeCode)
    );
    const snapshot = await getDocs(q);
    const reviews: FirestoreReviewDoc[] = [];
    snapshot.forEach((d) => {
      reviews.push({ id: d.id, ...d.data() } as FirestoreReviewDoc);
    });
    return reviews;
  } catch (err) {
    handleFirestoreError(err, OperationType.GET, REVIEWS_COLLECTION);
    return [];
  }
}
